site_url: https://hoopoes.github.io/CodersInventory
site_dir: build/site
site_name: CodersInventory
site_description: An Open Source Community for Code Snippets
site_author: Muhammad Umar Anzar & Mubashir Ahmed Siddiqui

repo_name: Hoopoes/CodersInventor
repo_url: https://github.com/Hoopoes/CodersInventory

copyright: |
  &copy; 2025 <a href="https://github.com/Hoopoes" target="_blank" rel="noopener">Hoopes</a>. Created by <a href="https://github.com/umar-anzar" target="_blank" rel="noopener">Muhammad Umar Anzar</a> and <a href="https://github.com/mubashirsidiki" target="_blank" rel="noopener">Mubashir Ahmed Siddiqui</a>. All rights reserved.

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/nVYeNaPFPK
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/hoopoes-opensource


strict: true

theme:
  custom_dir: overrides
  name: material
  language: en
  logo: https://cdn-icons-png.flaticon.com/512/12141/12141658.png
  favicon: https://cdn-icons-png.flaticon.com/64/12141/12141658.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top  # Keeps top bar but no tabs
    # - toc.integrate # commenting this result toc placed on right hand side
    - search.suggest
    - search.share
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dimmed mode
      primary: blue
      accent: purple
    - scheme: dimmed
      toggle:
        icon: material/weather-sunset
        name: Switch to dark mode
      primary: deep orange
      accent: yellow
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: lime
  plugins:
    - social
    - search:
      lang:
        - en
  icon:
    annotation: material/arrow-right-circle

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      title: Page contents

  

extra_css:
  - scripts/stylesheets/extra.css

extra_javascript:
  - scripts/javascripts/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML





nav:
  - Home: index.md
  - Docs & Markup:
    - Markdown Formatting: root/docs-and-markup/markdown.md
    - MkDocs Formatting: root/docs-and-markup/mkdocs.md
  - Code Snippets:
    - Validation Patterns:
      - Pydantic: root/code-snippets/validation-patterns/pydantic.md
  - Environment:
    - Setup Packages:
      - Deep Learning:
        - PyTorch with Poetry: root/environment/deep-learning/torch.md
        - TensorFlow with Poetry: root/environment/deep-learning/tensorflow.md 
      # - OCR: 
      #   - PaddleOCR: root/environment/ocr/paddleocr.md
      #   - EasyOCR: root/environment/ocr/easyocr.md

  - Machine Learning:
    - LLM Fine-Tuning:
      - LoRA: 
        - FlanT5: root/machine-Learning/llm-fine-tune/lora/flant5.md
    # - YOLO Model Pruning: machine-learning/yolo-pruning.md
  - Utilities: root/utilities/index.md
  #     - Cosine Similarity Metric: metrics/cosine-similarity.md
  - DevOps: root/devops/index.md
  #     - Nginx Configuration: devops/nginx-config.md
  #     - Docker Multi-Instance Setup: devops/docker-multi-instance.md
  #     - TCP Proxy for Database: devops/tcp-proxy.md
  - Databases: root/databases/index.md
  #     - Postgres TS Vector Script: databases/ts-vector.md

  # - User Guide:
  #   - Writing your docs: llm/gpt2.md
  #   - Styling your docs: llm/llm.md
  # - End:
  #   - bye: pagae_2.md

